---
title: "DEG identification using DESEQ"
author: "Hargunjeet Kaur"
date: "2024-08-01"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Install all packages

```         
if (!require("BiocManager", quietly = TRUE))
  install.packages("BiocManager")
BiocManager::install("DESeq2")

install.packages("ggplot2")
install.packages("gplots")
install.packages("readr")
install.packages("pheatmap")



if (!require("BiocManager", quietly = TRUE))
  install.packages("BiocManager")
BiocManager::install("EnhancedVolcano")


if (!require("BiocManager", quietly = TRUE))
  install.packages("BiocManager")
BiocManager::install("apeglm")
```

## Load all packages

```         
library(readr)
library(DESeq2)
library(ggplot2)
library(EnhancedVolcano)
```

## Read count matrix

#### Here the count matrix used had 18 control (C) samples and 18 disease (D) samples {style="color: darkblue"}

```         

ed <- read_csv("data_1.csv",col_types = cols(C1 = col_integer(), 
                                             C2 = col_integer(), 
                                             C3 = col_integer(), 
                                             C4 = col_integer(), 
                                             C5 = col_integer(),
                                             C6 = col_integer(), 
                                             C7 = col_integer(), 
                                             C8 = col_integer(), 
                                             C9 = col_integer(), 
                                             C10 = col_integer(),
                                             C11 = col_integer(),
                                             C12 = col_integer(),
                                             C13 = col_integer(),
                                             C14 = col_integer(),
                                             C15 = col_integer(),
                                             C16 = col_integer(),
                                             C17 = col_integer(),
                                             C18 = col_integer(),
                                             D1 = col_integer(),
                                             D2 = col_integer(),
                                             D3 = col_integer(),
                                             D4 = col_integer(),
                                             D5 = col_integer(),
                                             D6 = col_integer(),
                                             D7 = col_integer(),
                                             D8 = col_integer(),
                                             D9 = col_integer(),
                                             D10 = col_integer(),
                                             D11 = col_integer(),
                                             D12 = col_integer(),
                                             D13 = col_integer(),
                                             D14 = col_integer(),
                                             D15 = col_integer(),
                                             D16 = col_integer(),
                                             D17 = col_integer(),
                                             D18 = col_integer()))
```

## Primary Indexing CSV file

```         

counts <- data.frame(ed)
row.names(counts) <- counts$Geneid
counts
final<- counts [, -1]
head(final)
write.csv(final ,'data_primary_indexed_final.csv')
```

## Creating a factor variable

```         
condition <- factor(c("C","C","C","C","C","C","C","C","C","C","C","C","C","C","C","C","C","C","D","D","D","D","D","D","D","D","D","D","D","D","D","D","D","D","D","D"))
```

## Creating a data frame with condition as a column

```         
coldata <- data.frame(row.names = colnames(final), condition)
```

## Checking for missing values in the data frame

```         
any(is.na(final))
```

## Removing rows with missing values to create a new data frame

`Counts <- final[complete.cases(final), ]`

## Running DESeq

```         


dds <- DESeqDataSetFromMatrix(Counts,coldata,~condition)

dds <- DESeq(dds)

res <- results(dds, contrast = c("condition", "C", "D"))
```

## Viewing DESeq Results

```         
head(res)

summary(res)
```

## Filtering significant genes (sigs)

```         
sigs <- na.omit(res)
sigs <- sigs[sigs$padj < 0.05,]
```

## Applying Variance Stabilizing Transformation (VST) and plotting PCA graph:

#### The function vst() is used to stabilize the variance across the range of mean values, which makes the data more suitable for visualization and downstream analyses. {style="color:darkblue"}

```         
vsd <- vst(dds)
plotPCA(vsd)
plotPCA(vsd, ntop=500, "condition") #An alternate type of PCA plot for top 500 most variable genes.

```

## Filtering up-regulated and down-regulated genes

```         
down_genes <- sigs[sigs$log2FoldChange < 0,]
up_genes <- sigs[sigs$log2FoldChange > 0,]
```

## Saving all filtered dataframes as csv files

```         
write.csv(sigs, "sigs.csv")
write.csv(down_genes, "down_genes.csv")
write.csv(up_genes, "up_genes.csv")
```

## Generating dispersion plot

```         

plotDispEsts(dds)
```

## Generating Heatmap

```         

library(pheatmap)

de_genes <- rownames(sigs)

counts_de <- Counts[de_genes,]

pheatmap(counts_de, scale = "row", clustering_distance_rows = "correlation", 
         clustering_distance_cols = "euclidean", show_rownames = FALSE)
```

## Generating enhanced volcano plot with labels

```         
EnhancedVolcano(res,
                lab = as.character(rownames(res)),  
                x = 'log2FoldChange',
                y = 'padj',
                xlim = c(-5,5),  
                ylim = c(0, 7))
                
```


## Generating MA Plot

```
plotMA(res)
```

## Generating a 3d PCA plot

```


pca <- prcomp(t(assay(vsd))) # Performing PCA on data transformed previously by vst()

pca_data <- pca$x[, 1:3] #Extracting PCA into three parts

conditions <- coldata$condition
colors <- ifelse(conditions == "C", "pink", "darkgreen")

open3d()

plot3d(pca_data, size=2, type="s", box=F,
       xlab="PC1", ylab="PC2", zlab="PC3",
       col=colors)


bbox3d(color=c("#483D8B", "black"), emission="#483D8B",
       specular="#483D8B", shininess=1, alpha=0.8, nticks=3) #defining colours of the bounding box

legend3d("topright", legend = levels(conditions), pch = 16, col = c("pink", "darkgreen"))

```



